keys_en = [
    [
        {"name": "key_`", "def": "`", "shift": "~"},
        {"name": "key_1", "def": "1", "shift": "!"},
        {"name": "key_2", "def": "2", "shift": "@"},
        {"name": "key_3", "def": "3", "shift": "#"},
        {"name": "key_4", "def": "4", "shift": "$"},
        {"name": "key_5", "def": "5", "shift": "%"},
        {"name": "key_6", "def": "6", "shift": "^"},
        {"name": "key_7", "def": "7", "shift": "&"},
        {"name": "key_8", "def": "8", "shift": "*"},
        {"name": "key_9", "def": "9", "shift": "("},
        {"name": "key_0", "def": "0", "shift": ")"},
        {"name": "key_-", "def": "-", "shift": "_"},
        {"name": "key_=", "def": "=", "shift": "+"},
        {"name": "key_BACKSPACE", "def": "BACKSPACE", "shift": "BACKSPACE"},
    ],
    [
        {"name": "key_TAB", "def": "TAB", "shift": "TAB"},
        {"name": "key_Q", "def": "q", "shift": "Q"},
        {"name": "key_W", "def": "w", "shift": "W"},
        {"name": "key_E", "def": "e", "shift": "E"},
        {"name": "key_R", "def": "r", "shift": "R"},
        {"name": "key_T", "def": "t", "shift": "T"},
        {"name": "key_Y", "def": "y", "shift": "Y"},
        {"name": "key_U", "def": "u", "shift": "U"},
        {"name": "key_I", "def": "i", "shift": "I"},
        {"name": "key_O", "def": "o", "shift": "O"},
        {"name": "key_P", "def": "p", "shift": "P"},
        {"name": "key_[", "def": "[", "shift": "{"},
        {"name": "key_]", "def": "]", "shift": "}"},
        {"name": "key_\\", "def": "\\", "shift": "|"},
    ],
    [
        {"name": "key_CAPS", "def": "CAPS", "shift": "CAPS"},
        {"name": "key_A", "def": "a", "shift": "A"},
        {"name": "key_S", "def": "s", "shift": "S"},
        {"name": "key_D", "def": "d", "shift": "D"},
        {"name": "key_F", "def": "f", "shift": "F"},
        {"name": "key_G", "def": "g", "shift": "G"},
        {"name": "key_H", "def": "h", "shift": "H"},
        {"name": "key_J", "def": "j", "shift": "J"},
        {"name": "key_K", "def": "k", "shift": "K"},
        {"name": "key_L", "def": "l", "shift": "L"},
        {"name": "key_;", "def": ";", "shift": ":"},
        {"name": "key_'", "def": "'", "shift": '"'},
        {"name": "key_ENTER", "def": "ENTER", "shift": "ENTER"},
    ],
    [
        {"name": "key_SHIFT1", "def": "SHIFT", "shift": "SHIFT"},
        {"name": "key_Z", "def": "z", "shift": "Z"},
        {"name": "key_X", "def": "x", "shift": "X"},
        {"name": "key_C", "def": "c", "shift": "C"},
        {"name": "key_V", "def": "v", "shift": "V"},
        {"name": "key_B", "def": "b", "shift": "B"},
        {"name": "key_N", "def": "n", "shift": "N"},
        {"name": "key_M", "def": "m", "shift": "M"},
        {"name": "key_,", "def": ",", "shift": "<"},
        {"name": "key_.", "def": ".", "shift": ">"},
        {"name": "key_/", "def": "/", "shift": "?"},
        {"name": "key_SHIFT2", "def": "SHIFT", "shift": "SHIFT"},
    ],
    [
        {"name": "key_CTRL1", "def": "CTRL", "shift": "CTRL"},
        {"name": "key_ALT1", "def": "ALT", "shift": "ALT"},
        {"name": "key_SPACE", "def": " ", "shift": " "},
        {"name": "key_ALT1", "def": "ALT", "shift": "ALT"},
        {"name": "key_CTRL2", "def": "CTRL", "shift": "CTRL"},
    ],
]

keys_ru = [
    [
        {"name": "key_ё", "def": "ё", "shift": "Ё"},
        {"name": "key_1", "def": "1", "shift": "1"},
        {"name": "key_2", "def": "2", "shift": "2"},
        {"name": "key_3", "def": "3", "shift": "3"},
        {"name": "key_4", "def": "4", "shift": "4"},
        {"name": "key_5", "def": "5", "shift": "5"},
        {"name": "key_6", "def": "6", "shift": "6"},
        {"name": "key_7", "def": "7", "shift": "7"},
        {"name": "key_8", "def": "8", "shift": "8"},
        {"name": "key_9", "def": "9", "shift": "9"},
        {"name": "key_0", "def": "0", "shift": "0"},
        {"name": "key_-", "def": "-", "shift": "-"},
        {"name": "key_+", "def": "+", "shift": "+"},
        {"name": "key_BACKSPACE", "def": "BACKSPACE", "shift": "BACKSPACE"},
    ],
    [
        {"name": "key_TAB", "def": "TAB", "shift": "TAB"},
        {"name": "key_й", "def": "й", "shift": "Й"},
        {"name": "key_ц", "def": "ц", "shift": "Ц"},
        {"name": "key_у", "def": "у", "shift": "У"},
        {"name": "key_к", "def": "к", "shift": "К"},
        {"name": "key_е", "def": "е", "shift": "Е"},
        {"name": "key_н", "def": "н", "shift": "Н"},
        {"name": "key_г", "def": "г", "shift": "Г"},
        {"name": "key_ш", "def": "ш", "shift": "Ш"},
        {"name": "key_щ", "def": "щ", "shift": "Щ"},
        {"name": "key_з", "def": "з", "shift": "З"},
        {"name": "key_х", "def": "х", "shift": "Х"},
        {"name": "key_ъ", "def": "ъ", "shift": "Ъ"},
        {"name": "key_\\", "def": "\\", "shift": "\\"},
    ],
    [
        {"name": "key_CAPS", "def": "CAPS", "shift": "CAPS"},
        {"name": "key_ф", "def": "ф", "shift": "Ф"},
        {"name": "key_ы", "def": "ы", "shift": "Ы"},
        {"name": "key_в", "def": "в", "shift": "В"},
        {"name": "key_а", "def": "а", "shift": "А"},
        {"name": "key_п", "def": "п", "shift": "П"},
        {"name": "key_р", "def": "р", "shift": "Р"},
        {"name": "key_о", "def": "о", "shift": "О"},
        {"name": "key_л", "def": "л", "shift": "Л"},
        {"name": "key_д", "def": "д", "shift": "Д"},
        {"name": "key_ж", "def": "ж", "shift": "Ж"},
        {"name": "key_э", "def": "э", "shift": "Э"},
        {"name": "key_ENTER", "def": "ENTER", "shift": "ENTER"},
    ],
    [
        {"name": "key_SHIFT1", "def": "SHIFT", "shift": "SHIFT"},
        {"name": "key_я", "def": "я", "shift": "Я"},
        {"name": "key_ч", "def": "ч", "shift": "Ч"},
        {"name": "key_с", "def": "с", "shift": "С"},
        {"name": "key_м", "def": "м", "shift": "М"},
        {"name": "key_и", "def": "и", "shift": "И"},
        {"name": "key_т", "def": "т", "shift": "Т"},
        {"name": "key_ь", "def": "ь", "shift": "Ь"},
        {"name": "key_б", "def": "б", "shift": "Б"},
        {"name": "key_ю", "def": "ю", "shift": "Ю"},
        {"name": "key_.", "def": ".", "shift": "."},
        {"name": "key_SHIFT2", "def": "SHIFT", "shift": "SHIFT"},
    ],
    [
        {"name": "key_CTRL1", "def": "CTRL", "shift": "CTRL"},
        {"name": "key_ALT1", "def": "ALT", "shift": "ALT"},
        {"name": "key_SPACE", "def": " ", "shift": " "},
        {"name": "key_ALT1", "def": "ALT", "shift": "ALT"},
        {"name": "key_CTRL2", "def": "CTRL", "shift": "CTRL"},
    ],
]

for row in keys_ru:
    for i in range(len(row)):
        row[i] = {'name':'key_'+row[i], 'def':row[i], 'shift':row[i].upper()}

print(keys_ru)
